// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: uml.proto
// Protobuf C++ Version: 6.31.1

#include "uml.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace uml {
}  // namespace uml
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_uml_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_uml_2eproto = nullptr;
const ::uint32_t TableStruct_uml_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_uml_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tuml.proto\022\003uml\032 google/protobuf/descri"
    "ptor.proto:>\n\025option_parent_message\022\035.go"
    "ogle.protobuf.FieldOptions\030\320\206\003 \001(\010:>\n\025op"
    "tion_required_field\022\035.google.protobuf.Fi"
    "eldOptions\030\321\206\003 \001(\010:@\n\027option_multiplicit"
    "y_min\022\035.google.protobuf.FieldOptions\030\322\206\003"
    " \001(\005:@\n\027option_multiplicity_max\022\035.google"
    ".protobuf.FieldOptions\030\323\206\003 \001(\005:4\n\013option"
    "_uuid\022\035.google.protobuf.FieldOptions\030\324\206\003"
    " \001(\010:3\n\noption_key\022\035.google.protobuf.Fie"
    "ldOptions\030\325\206\003 \001(\010:A\n\026option_openfmb_prof"
    "ile\022\037.google.protobuf.MessageOptions\030\270\216\003"
    " \001(\010B]\n\007openfmbP\001ZFgitlab.com/openfmb/ps"
    "m/ops/protobuf/go-openfmb-ops-protobuf/v"
    "2/openfmb\252\002\007openfmbb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_uml_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_uml_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_uml_2eproto = {
    false,
    false,
    587,
    descriptor_table_protodef_uml_2eproto,
    "uml.proto",
    &descriptor_table_uml_2eproto_once,
    descriptor_table_uml_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_uml_2eproto::offsets,
    file_level_enum_descriptors_uml_2eproto,
    file_level_service_descriptors_uml_2eproto,
};
namespace uml {
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        option_parent_message(kOptionParentMessageFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        option_required_field(kOptionRequiredFieldFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::int32_t >, 5, false>
        option_multiplicity_min(kOptionMultiplicityMinFieldNumber, 0);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< ::int32_t >, 5, false>
        option_multiplicity_max(kOptionMultiplicityMaxFieldNumber, 0);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        option_uuid(kOptionUuidFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::FieldOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        option_key(kOptionKeyFieldNumber, false);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::MessageOptions, ::_pbi::PrimitiveTypeTraits< bool >, 8, false>
        option_openfmb_profile(kOptionOpenfmbProfileFieldNumber, false);
// @@protoc_insertion_point(namespace_scope)
}  // namespace uml
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_uml_2eproto),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50000, 8,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50001, 8,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50002, 5,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50003, 5,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50004, 8,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FieldOptions::default_instance(), 50005, 8,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::MessageOptions::default_instance(), 51000, 8,
            false, false),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
