// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uml.proto

#include "uml.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace uml {
}  // namespace uml
void InitDefaults_uml_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_uml_2eproto = nullptr;
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_uml_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_uml_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_uml_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = nullptr;
static constexpr ::google::protobuf::Message* const* file_default_instances = nullptr;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_uml_2eproto = {
  {}, AddDescriptors_uml_2eproto, "uml.proto", schemas,
  file_default_instances, TableStruct_uml_2eproto::offsets,
  file_level_metadata_uml_2eproto, 0, file_level_enum_descriptors_uml_2eproto, file_level_service_descriptors_uml_2eproto,
};

const char descriptor_table_protodef_uml_2eproto[] =
  "\n\tuml.proto\022\003uml\032 google/protobuf/descri"
  "ptor.proto:>\n\025option_parent_message\022\035.go"
  "ogle.protobuf.FieldOptions\030\320\206\003 \001(\010:>\n\025op"
  "tion_required_field\022\035.google.protobuf.Fi"
  "eldOptions\030\321\206\003 \001(\010:@\n\027option_multiplicit"
  "y_min\022\035.google.protobuf.FieldOptions\030\322\206\003"
  " \001(\005:@\n\027option_multiplicity_max\022\035.google"
  ".protobuf.FieldOptions\030\323\206\003 \001(\005:4\n\013option"
  "_uuid\022\035.google.protobuf.FieldOptions\030\324\206\003"
  " \001(\010:3\n\noption_key\022\035.google.protobuf.Fie"
  "ldOptions\030\325\206\003 \001(\010:A\n\026option_openfmb_prof"
  "ile\022\037.google.protobuf.MessageOptions\030\270\216\003"
  " \001(\010BZ\n\007openfmbP\001ZCgitlab.com/openfmb/ps"
  "m/ops/protobuf/go-openfmb-ops-protobuf/o"
  "penfmb\252\002\007openfmbb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_uml_2eproto = {
  false, InitDefaults_uml_2eproto, 
  descriptor_table_protodef_uml_2eproto,
  "uml.proto", &assign_descriptors_table_uml_2eproto, 584,
};

void AddDescriptors_uml_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2fdescriptor_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_uml_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_uml_2eproto = []() { AddDescriptors_uml_2eproto(); return true; }();
namespace uml {
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  option_parent_message(kOptionParentMessageFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  option_required_field(kOptionRequiredFieldFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  option_multiplicity_min(kOptionMultiplicityMinFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  option_multiplicity_max(kOptionMultiplicityMaxFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  option_uuid(kOptionUuidFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  option_key(kOptionKeyFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  option_openfmb_profile(kOptionOpenfmbProfileFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)
}  // namespace uml
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
