// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: environmentmodule/environmentmodule.proto
// Protobuf C++ Version: 6.31.1

#include "environmentmodule/environmentmodule.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace environmentmodule {

inline constexpr EnvironmentReading::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        conductingequipmentterminalreading_{nullptr},
        readingmenv_{nullptr},
        readingmmet_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR EnvironmentReading::EnvironmentReading(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EnvironmentReading_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnvironmentReadingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentReadingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentReadingDefaultTypeInternal() {}
  union {
    EnvironmentReading _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentReadingDefaultTypeInternal _EnvironmentReading_default_instance_;

inline constexpr EnvironmentReadingProfile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        readingmessageinfo_{nullptr},
        sensor_{nullptr},
        environmentreading_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR EnvironmentReadingProfile::EnvironmentReadingProfile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EnvironmentReadingProfile_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnvironmentReadingProfileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvironmentReadingProfileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvironmentReadingProfileDefaultTypeInternal() {}
  union {
    EnvironmentReadingProfile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvironmentReadingProfileDefaultTypeInternal _EnvironmentReadingProfile_default_instance_;
}  // namespace environmentmodule
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_environmentmodule_2fenvironmentmodule_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_environmentmodule_2fenvironmentmodule_2eproto = nullptr;
const ::uint32_t
    TableStruct_environmentmodule_2fenvironmentmodule_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReading, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReading, _impl_.conductingequipmentterminalreading_),
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReading, _impl_.readingmenv_),
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReading, _impl_.readingmmet_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReadingProfile, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReadingProfile, _impl_.readingmessageinfo_),
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReadingProfile, _impl_.sensor_),
        PROTOBUF_FIELD_OFFSET(::environmentmodule::EnvironmentReadingProfile, _impl_.environmentreading_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::environmentmodule::EnvironmentReading)},
        {9, sizeof(::environmentmodule::EnvironmentReadingProfile)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::environmentmodule::_EnvironmentReading_default_instance_._instance,
    &::environmentmodule::_EnvironmentReadingProfile_default_instance_._instance,
};
const char descriptor_table_protodef_environmentmodule_2fenvironmentmodule_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n)environmentmodule/environmentmodule.pr"
    "oto\022\021environmentmodule\032\tuml.proto\032\037commo"
    "nmodule/commonmodule.proto\"\330\001\n\022Environme"
    "ntReading\022b\n\"conductingEquipmentTerminal"
    "Reading\030\001 \001(\01320.commonmodule.ConductingE"
    "quipmentTerminalReadingB\004\200\265\030\001\022.\n\013reading"
    "MENV\030\002 \001(\0132\031.commonmodule.ReadingMENV\022.\n"
    "\013readingMMET\030\003 \001(\0132\031.commonmodule.Readin"
    "gMMET\"\342\001\n\031EnvironmentReadingProfile\022B\n\022r"
    "eadingMessageInfo\030\001 \001(\0132 .commonmodule.R"
    "eadingMessageInfoB\004\200\265\030\001\022.\n\006sensor\030\002 \001(\0132"
    "\024.commonmodule.SensorB\010\210\265\030\001\220\265\030\001\022K\n\022envir"
    "onmentReading\030\003 \001(\0132%.environmentmodule."
    "EnvironmentReadingB\010\210\265\030\001\220\265\030\001:\004\300\363\030\001B\223\001\n\031o"
    "penfmb.environmentmoduleP\001ZXgitlab.com/o"
    "penfmb/psm/ops/protobuf/go-openfmb-ops-p"
    "rotobuf/v2/openfmb/environmentmodule\252\002\031o"
    "penfmb.environmentmoduleb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_environmentmodule_2fenvironmentmodule_2eproto_deps[2] = {
        &::descriptor_table_commonmodule_2fcommonmodule_2eproto,
        &::descriptor_table_uml_2eproto,
};
static ::absl::once_flag descriptor_table_environmentmodule_2fenvironmentmodule_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_environmentmodule_2fenvironmentmodule_2eproto = {
    false,
    false,
    712,
    descriptor_table_protodef_environmentmodule_2fenvironmentmodule_2eproto,
    "environmentmodule/environmentmodule.proto",
    &descriptor_table_environmentmodule_2fenvironmentmodule_2eproto_once,
    descriptor_table_environmentmodule_2fenvironmentmodule_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_environmentmodule_2fenvironmentmodule_2eproto::offsets,
    file_level_enum_descriptors_environmentmodule_2fenvironmentmodule_2eproto,
    file_level_service_descriptors_environmentmodule_2fenvironmentmodule_2eproto,
};
namespace environmentmodule {
// ===================================================================

class EnvironmentReading::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EnvironmentReading>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_._has_bits_);
};

void EnvironmentReading::clear_conductingequipmentterminalreading() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.conductingequipmentterminalreading_ != nullptr) _impl_.conductingequipmentterminalreading_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void EnvironmentReading::clear_readingmenv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.readingmenv_ != nullptr) _impl_.readingmenv_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void EnvironmentReading::clear_readingmmet() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.readingmmet_ != nullptr) _impl_.readingmmet_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
EnvironmentReading::EnvironmentReading(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentReading_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:environmentmodule.EnvironmentReading)
}
PROTOBUF_NDEBUG_INLINE EnvironmentReading::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::environmentmodule::EnvironmentReading& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

EnvironmentReading::EnvironmentReading(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EnvironmentReading& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentReading_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EnvironmentReading* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.conductingequipmentterminalreading_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.conductingequipmentterminalreading_)
                : nullptr;
  _impl_.readingmenv_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.readingmenv_)
                : nullptr;
  _impl_.readingmmet_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.readingmmet_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:environmentmodule.EnvironmentReading)
}
PROTOBUF_NDEBUG_INLINE EnvironmentReading::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void EnvironmentReading::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, conductingequipmentterminalreading_),
           0,
           offsetof(Impl_, readingmmet_) -
               offsetof(Impl_, conductingequipmentterminalreading_) +
               sizeof(Impl_::readingmmet_));
}
EnvironmentReading::~EnvironmentReading() {
  // @@protoc_insertion_point(destructor:environmentmodule.EnvironmentReading)
  SharedDtor(*this);
}
inline void EnvironmentReading::SharedDtor(MessageLite& self) {
  EnvironmentReading& this_ = static_cast<EnvironmentReading&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.conductingequipmentterminalreading_;
  delete this_._impl_.readingmenv_;
  delete this_._impl_.readingmmet_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EnvironmentReading::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EnvironmentReading(arena);
}
constexpr auto EnvironmentReading::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnvironmentReading),
                                            alignof(EnvironmentReading));
}
constexpr auto EnvironmentReading::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EnvironmentReading_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EnvironmentReading::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EnvironmentReading>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EnvironmentReading::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EnvironmentReading>(), &EnvironmentReading::ByteSizeLong,
              &EnvironmentReading::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_._cached_size_),
          false,
      },
      &EnvironmentReading::kDescriptorMethods,
      &descriptor_table_environmentmodule_2fenvironmentmodule_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EnvironmentReading_class_data_ =
        EnvironmentReading::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EnvironmentReading::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EnvironmentReading_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EnvironmentReading_class_data_.tc_table);
  return EnvironmentReading_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2>
EnvironmentReading::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EnvironmentReading_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::environmentmodule::EnvironmentReading>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .commonmodule.ConductingEquipmentTerminalReading conductingEquipmentTerminalReading = 1 [(.uml.option_parent_message) = true];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.conductingequipmentterminalreading_)}},
    // .commonmodule.ReadingMENV readingMENV = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.readingmenv_)}},
    // .commonmodule.ReadingMMET readingMMET = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.readingmmet_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .commonmodule.ConductingEquipmentTerminalReading conductingEquipmentTerminalReading = 1 [(.uml.option_parent_message) = true];
    {PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.conductingequipmentterminalreading_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .commonmodule.ReadingMENV readingMENV = 2;
    {PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.readingmenv_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .commonmodule.ReadingMMET readingMMET = 3;
    {PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.readingmmet_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::commonmodule::ConductingEquipmentTerminalReading>()},
      {::_pbi::TcParser::GetTable<::commonmodule::ReadingMENV>()},
      {::_pbi::TcParser::GetTable<::commonmodule::ReadingMMET>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void EnvironmentReading::Clear() {
// @@protoc_insertion_point(message_clear_start:environmentmodule.EnvironmentReading)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.conductingequipmentterminalreading_ != nullptr);
      _impl_.conductingequipmentterminalreading_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.readingmenv_ != nullptr);
      _impl_.readingmenv_->Clear();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.readingmmet_ != nullptr);
      _impl_.readingmmet_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EnvironmentReading::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EnvironmentReading& this_ = static_cast<const EnvironmentReading&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EnvironmentReading::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EnvironmentReading& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:environmentmodule.EnvironmentReading)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .commonmodule.ConductingEquipmentTerminalReading conductingEquipmentTerminalReading = 1 [(.uml.option_parent_message) = true];
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.conductingequipmentterminalreading_, this_._impl_.conductingequipmentterminalreading_->GetCachedSize(), target,
        stream);
  }

  // .commonmodule.ReadingMENV readingMENV = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.readingmenv_, this_._impl_.readingmenv_->GetCachedSize(), target,
        stream);
  }

  // .commonmodule.ReadingMMET readingMMET = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.readingmmet_, this_._impl_.readingmmet_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:environmentmodule.EnvironmentReading)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EnvironmentReading::ByteSizeLong(const MessageLite& base) {
  const EnvironmentReading& this_ = static_cast<const EnvironmentReading&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EnvironmentReading::ByteSizeLong() const {
  const EnvironmentReading& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:environmentmodule.EnvironmentReading)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // .commonmodule.ConductingEquipmentTerminalReading conductingEquipmentTerminalReading = 1 [(.uml.option_parent_message) = true];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.conductingequipmentterminalreading_);
    }
    // .commonmodule.ReadingMENV readingMENV = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.readingmenv_);
    }
    // .commonmodule.ReadingMMET readingMMET = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.readingmmet_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EnvironmentReading::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnvironmentReading*>(&to_msg);
  auto& from = static_cast<const EnvironmentReading&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:environmentmodule.EnvironmentReading)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.conductingequipmentterminalreading_ != nullptr);
      if (_this->_impl_.conductingequipmentterminalreading_ == nullptr) {
        _this->_impl_.conductingequipmentterminalreading_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.conductingequipmentterminalreading_);
      } else {
        _this->_impl_.conductingequipmentterminalreading_->MergeFrom(*from._impl_.conductingequipmentterminalreading_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.readingmenv_ != nullptr);
      if (_this->_impl_.readingmenv_ == nullptr) {
        _this->_impl_.readingmenv_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.readingmenv_);
      } else {
        _this->_impl_.readingmenv_->MergeFrom(*from._impl_.readingmenv_);
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.readingmmet_ != nullptr);
      if (_this->_impl_.readingmmet_ == nullptr) {
        _this->_impl_.readingmmet_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.readingmmet_);
      } else {
        _this->_impl_.readingmmet_->MergeFrom(*from._impl_.readingmmet_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnvironmentReading::CopyFrom(const EnvironmentReading& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:environmentmodule.EnvironmentReading)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnvironmentReading::InternalSwap(EnvironmentReading* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.readingmmet_)
      + sizeof(EnvironmentReading::_impl_.readingmmet_)
      - PROTOBUF_FIELD_OFFSET(EnvironmentReading, _impl_.conductingequipmentterminalreading_)>(
          reinterpret_cast<char*>(&_impl_.conductingequipmentterminalreading_),
          reinterpret_cast<char*>(&other->_impl_.conductingequipmentterminalreading_));
}

::google::protobuf::Metadata EnvironmentReading::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EnvironmentReadingProfile::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EnvironmentReadingProfile>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_._has_bits_);
};

void EnvironmentReadingProfile::clear_readingmessageinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.readingmessageinfo_ != nullptr) _impl_.readingmessageinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void EnvironmentReadingProfile::clear_sensor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sensor_ != nullptr) _impl_.sensor_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
EnvironmentReadingProfile::EnvironmentReadingProfile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentReadingProfile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:environmentmodule.EnvironmentReadingProfile)
}
PROTOBUF_NDEBUG_INLINE EnvironmentReadingProfile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::environmentmodule::EnvironmentReadingProfile& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

EnvironmentReadingProfile::EnvironmentReadingProfile(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EnvironmentReadingProfile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EnvironmentReadingProfile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EnvironmentReadingProfile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.readingmessageinfo_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.readingmessageinfo_)
                : nullptr;
  _impl_.sensor_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sensor_)
                : nullptr;
  _impl_.environmentreading_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.environmentreading_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:environmentmodule.EnvironmentReadingProfile)
}
PROTOBUF_NDEBUG_INLINE EnvironmentReadingProfile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void EnvironmentReadingProfile::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, readingmessageinfo_),
           0,
           offsetof(Impl_, environmentreading_) -
               offsetof(Impl_, readingmessageinfo_) +
               sizeof(Impl_::environmentreading_));
}
EnvironmentReadingProfile::~EnvironmentReadingProfile() {
  // @@protoc_insertion_point(destructor:environmentmodule.EnvironmentReadingProfile)
  SharedDtor(*this);
}
inline void EnvironmentReadingProfile::SharedDtor(MessageLite& self) {
  EnvironmentReadingProfile& this_ = static_cast<EnvironmentReadingProfile&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.readingmessageinfo_;
  delete this_._impl_.sensor_;
  delete this_._impl_.environmentreading_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EnvironmentReadingProfile::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EnvironmentReadingProfile(arena);
}
constexpr auto EnvironmentReadingProfile::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnvironmentReadingProfile),
                                            alignof(EnvironmentReadingProfile));
}
constexpr auto EnvironmentReadingProfile::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EnvironmentReadingProfile_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EnvironmentReadingProfile::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EnvironmentReadingProfile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EnvironmentReadingProfile::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EnvironmentReadingProfile>(), &EnvironmentReadingProfile::ByteSizeLong,
              &EnvironmentReadingProfile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_._cached_size_),
          false,
      },
      &EnvironmentReadingProfile::kDescriptorMethods,
      &descriptor_table_environmentmodule_2fenvironmentmodule_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EnvironmentReadingProfile_class_data_ =
        EnvironmentReadingProfile::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EnvironmentReadingProfile::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EnvironmentReadingProfile_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EnvironmentReadingProfile_class_data_.tc_table);
  return EnvironmentReadingProfile_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2>
EnvironmentReadingProfile::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EnvironmentReadingProfile_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::environmentmodule::EnvironmentReadingProfile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.readingmessageinfo_)}},
    // .commonmodule.Sensor sensor = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.sensor_)}},
    // .environmentmodule.EnvironmentReading environmentReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.environmentreading_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];
    {PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.readingmessageinfo_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .commonmodule.Sensor sensor = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
    {PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.sensor_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .environmentmodule.EnvironmentReading environmentReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
    {PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.environmentreading_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::commonmodule::ReadingMessageInfo>()},
      {::_pbi::TcParser::GetTable<::commonmodule::Sensor>()},
      {::_pbi::TcParser::GetTable<::environmentmodule::EnvironmentReading>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void EnvironmentReadingProfile::Clear() {
// @@protoc_insertion_point(message_clear_start:environmentmodule.EnvironmentReadingProfile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.readingmessageinfo_ != nullptr);
      _impl_.readingmessageinfo_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.sensor_ != nullptr);
      _impl_.sensor_->Clear();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.environmentreading_ != nullptr);
      _impl_.environmentreading_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EnvironmentReadingProfile::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EnvironmentReadingProfile& this_ = static_cast<const EnvironmentReadingProfile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EnvironmentReadingProfile::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EnvironmentReadingProfile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:environmentmodule.EnvironmentReadingProfile)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.readingmessageinfo_, this_._impl_.readingmessageinfo_->GetCachedSize(), target,
        stream);
  }

  // .commonmodule.Sensor sensor = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.sensor_, this_._impl_.sensor_->GetCachedSize(), target,
        stream);
  }

  // .environmentmodule.EnvironmentReading environmentReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.environmentreading_, this_._impl_.environmentreading_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:environmentmodule.EnvironmentReadingProfile)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EnvironmentReadingProfile::ByteSizeLong(const MessageLite& base) {
  const EnvironmentReadingProfile& this_ = static_cast<const EnvironmentReadingProfile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EnvironmentReadingProfile::ByteSizeLong() const {
  const EnvironmentReadingProfile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:environmentmodule.EnvironmentReadingProfile)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // .commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.readingmessageinfo_);
    }
    // .commonmodule.Sensor sensor = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.sensor_);
    }
    // .environmentmodule.EnvironmentReading environmentReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.environmentreading_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EnvironmentReadingProfile::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnvironmentReadingProfile*>(&to_msg);
  auto& from = static_cast<const EnvironmentReadingProfile&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:environmentmodule.EnvironmentReadingProfile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.readingmessageinfo_ != nullptr);
      if (_this->_impl_.readingmessageinfo_ == nullptr) {
        _this->_impl_.readingmessageinfo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.readingmessageinfo_);
      } else {
        _this->_impl_.readingmessageinfo_->MergeFrom(*from._impl_.readingmessageinfo_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.sensor_ != nullptr);
      if (_this->_impl_.sensor_ == nullptr) {
        _this->_impl_.sensor_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sensor_);
      } else {
        _this->_impl_.sensor_->MergeFrom(*from._impl_.sensor_);
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.environmentreading_ != nullptr);
      if (_this->_impl_.environmentreading_ == nullptr) {
        _this->_impl_.environmentreading_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.environmentreading_);
      } else {
        _this->_impl_.environmentreading_->MergeFrom(*from._impl_.environmentreading_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnvironmentReadingProfile::CopyFrom(const EnvironmentReadingProfile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:environmentmodule.EnvironmentReadingProfile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnvironmentReadingProfile::InternalSwap(EnvironmentReadingProfile* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.environmentreading_)
      + sizeof(EnvironmentReadingProfile::_impl_.environmentreading_)
      - PROTOBUF_FIELD_OFFSET(EnvironmentReadingProfile, _impl_.readingmessageinfo_)>(
          reinterpret_cast<char*>(&_impl_.readingmessageinfo_),
          reinterpret_cast<char*>(&other->_impl_.readingmessageinfo_));
}

::google::protobuf::Metadata EnvironmentReadingProfile::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace environmentmodule
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_environmentmodule_2fenvironmentmodule_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
