// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resourcemodule/resourcemodule.proto

#ifndef PROTOBUF_INCLUDED_resourcemodule_2fresourcemodule_2eproto
#define PROTOBUF_INCLUDED_resourcemodule_2fresourcemodule_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "uml.pb.h"
#include "commonmodule/commonmodule.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_resourcemodule_2fresourcemodule_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_resourcemodule_2fresourcemodule_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_resourcemodule_2fresourcemodule_2eproto();
namespace resourcemodule {
class ResourceReading;
class ResourceReadingDefaultTypeInternal;
extern ResourceReadingDefaultTypeInternal _ResourceReading_default_instance_;
class ResourceReadingProfile;
class ResourceReadingProfileDefaultTypeInternal;
extern ResourceReadingProfileDefaultTypeInternal _ResourceReadingProfile_default_instance_;
class ResourceStatus;
class ResourceStatusDefaultTypeInternal;
extern ResourceStatusDefaultTypeInternal _ResourceStatus_default_instance_;
class ResourceStatusProfile;
class ResourceStatusProfileDefaultTypeInternal;
extern ResourceStatusProfileDefaultTypeInternal _ResourceStatusProfile_default_instance_;
}  // namespace resourcemodule
namespace google {
namespace protobuf {
template<> ::resourcemodule::ResourceReading* Arena::CreateMaybeMessage<::resourcemodule::ResourceReading>(Arena*);
template<> ::resourcemodule::ResourceReadingProfile* Arena::CreateMaybeMessage<::resourcemodule::ResourceReadingProfile>(Arena*);
template<> ::resourcemodule::ResourceStatus* Arena::CreateMaybeMessage<::resourcemodule::ResourceStatus>(Arena*);
template<> ::resourcemodule::ResourceStatusProfile* Arena::CreateMaybeMessage<::resourcemodule::ResourceStatusProfile>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace resourcemodule {

// ===================================================================

class ResourceReading :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:resourcemodule.ResourceReading) */ {
 public:
  ResourceReading();
  virtual ~ResourceReading();

  ResourceReading(const ResourceReading& from);

  inline ResourceReading& operator=(const ResourceReading& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResourceReading(ResourceReading&& from) noexcept
    : ResourceReading() {
    *this = ::std::move(from);
  }

  inline ResourceReading& operator=(ResourceReading&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ResourceReading& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResourceReading* internal_default_instance() {
    return reinterpret_cast<const ResourceReading*>(
               &_ResourceReading_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ResourceReading* other);
  friend void swap(ResourceReading& a, ResourceReading& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResourceReading* New() const final {
    return CreateMaybeMessage<ResourceReading>(nullptr);
  }

  ResourceReading* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResourceReading>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResourceReading& from);
  void MergeFrom(const ResourceReading& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceReading* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .commonmodule.ConductingEquipmentTerminalReading conductingEquipmentTerminalReading = 1 [(.uml.option_parent_message) = true];
  bool has_conductingequipmentterminalreading() const;
  void clear_conductingequipmentterminalreading();
  static const int kConductingEquipmentTerminalReadingFieldNumber = 1;
  const ::commonmodule::ConductingEquipmentTerminalReading& conductingequipmentterminalreading() const;
  ::commonmodule::ConductingEquipmentTerminalReading* release_conductingequipmentterminalreading();
  ::commonmodule::ConductingEquipmentTerminalReading* mutable_conductingequipmentterminalreading();
  void set_allocated_conductingequipmentterminalreading(::commonmodule::ConductingEquipmentTerminalReading* conductingequipmentterminalreading);

  // .commonmodule.PhaseMMTN phaseMMTN = 2;
  bool has_phasemmtn() const;
  void clear_phasemmtn();
  static const int kPhaseMMTNFieldNumber = 2;
  const ::commonmodule::PhaseMMTN& phasemmtn() const;
  ::commonmodule::PhaseMMTN* release_phasemmtn();
  ::commonmodule::PhaseMMTN* mutable_phasemmtn();
  void set_allocated_phasemmtn(::commonmodule::PhaseMMTN* phasemmtn);

  // .commonmodule.ReadingMMTR readingMMTR = 3;
  bool has_readingmmtr() const;
  void clear_readingmmtr();
  static const int kReadingMMTRFieldNumber = 3;
  const ::commonmodule::ReadingMMTR& readingmmtr() const;
  ::commonmodule::ReadingMMTR* release_readingmmtr();
  ::commonmodule::ReadingMMTR* mutable_readingmmtr();
  void set_allocated_readingmmtr(::commonmodule::ReadingMMTR* readingmmtr);

  // .commonmodule.ReadingMMXU readingMMXU = 4;
  bool has_readingmmxu() const;
  void clear_readingmmxu();
  static const int kReadingMMXUFieldNumber = 4;
  const ::commonmodule::ReadingMMXU& readingmmxu() const;
  ::commonmodule::ReadingMMXU* release_readingmmxu();
  ::commonmodule::ReadingMMXU* mutable_readingmmxu();
  void set_allocated_readingmmxu(::commonmodule::ReadingMMXU* readingmmxu);

  // @@protoc_insertion_point(class_scope:resourcemodule.ResourceReading)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::commonmodule::ConductingEquipmentTerminalReading* conductingequipmentterminalreading_;
  ::commonmodule::PhaseMMTN* phasemmtn_;
  ::commonmodule::ReadingMMTR* readingmmtr_;
  ::commonmodule::ReadingMMXU* readingmmxu_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_resourcemodule_2fresourcemodule_2eproto;
};
// -------------------------------------------------------------------

class ResourceReadingProfile :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:resourcemodule.ResourceReadingProfile) */ {
 public:
  ResourceReadingProfile();
  virtual ~ResourceReadingProfile();

  ResourceReadingProfile(const ResourceReadingProfile& from);

  inline ResourceReadingProfile& operator=(const ResourceReadingProfile& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResourceReadingProfile(ResourceReadingProfile&& from) noexcept
    : ResourceReadingProfile() {
    *this = ::std::move(from);
  }

  inline ResourceReadingProfile& operator=(ResourceReadingProfile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ResourceReadingProfile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResourceReadingProfile* internal_default_instance() {
    return reinterpret_cast<const ResourceReadingProfile*>(
               &_ResourceReadingProfile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ResourceReadingProfile* other);
  friend void swap(ResourceReadingProfile& a, ResourceReadingProfile& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResourceReadingProfile* New() const final {
    return CreateMaybeMessage<ResourceReadingProfile>(nullptr);
  }

  ResourceReadingProfile* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResourceReadingProfile>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResourceReadingProfile& from);
  void MergeFrom(const ResourceReadingProfile& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceReadingProfile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];
  bool has_readingmessageinfo() const;
  void clear_readingmessageinfo();
  static const int kReadingMessageInfoFieldNumber = 1;
  const ::commonmodule::ReadingMessageInfo& readingmessageinfo() const;
  ::commonmodule::ReadingMessageInfo* release_readingmessageinfo();
  ::commonmodule::ReadingMessageInfo* mutable_readingmessageinfo();
  void set_allocated_readingmessageinfo(::commonmodule::ReadingMessageInfo* readingmessageinfo);

  // .commonmodule.ConductingEquipment conductingEquipment = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  bool has_conductingequipment() const;
  void clear_conductingequipment();
  static const int kConductingEquipmentFieldNumber = 2;
  const ::commonmodule::ConductingEquipment& conductingequipment() const;
  ::commonmodule::ConductingEquipment* release_conductingequipment();
  ::commonmodule::ConductingEquipment* mutable_conductingequipment();
  void set_allocated_conductingequipment(::commonmodule::ConductingEquipment* conductingequipment);

  // .commonmodule.IED ied = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  bool has_ied() const;
  void clear_ied();
  static const int kIedFieldNumber = 3;
  const ::commonmodule::IED& ied() const;
  ::commonmodule::IED* release_ied();
  ::commonmodule::IED* mutable_ied();
  void set_allocated_ied(::commonmodule::IED* ied);

  // .resourcemodule.ResourceReading resourceReading = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  bool has_resourcereading() const;
  void clear_resourcereading();
  static const int kResourceReadingFieldNumber = 4;
  const ::resourcemodule::ResourceReading& resourcereading() const;
  ::resourcemodule::ResourceReading* release_resourcereading();
  ::resourcemodule::ResourceReading* mutable_resourcereading();
  void set_allocated_resourcereading(::resourcemodule::ResourceReading* resourcereading);

  // @@protoc_insertion_point(class_scope:resourcemodule.ResourceReadingProfile)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::commonmodule::ReadingMessageInfo* readingmessageinfo_;
  ::commonmodule::ConductingEquipment* conductingequipment_;
  ::commonmodule::IED* ied_;
  ::resourcemodule::ResourceReading* resourcereading_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_resourcemodule_2fresourcemodule_2eproto;
};
// -------------------------------------------------------------------

class ResourceStatus :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:resourcemodule.ResourceStatus) */ {
 public:
  ResourceStatus();
  virtual ~ResourceStatus();

  ResourceStatus(const ResourceStatus& from);

  inline ResourceStatus& operator=(const ResourceStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResourceStatus(ResourceStatus&& from) noexcept
    : ResourceStatus() {
    *this = ::std::move(from);
  }

  inline ResourceStatus& operator=(ResourceStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ResourceStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResourceStatus* internal_default_instance() {
    return reinterpret_cast<const ResourceStatus*>(
               &_ResourceStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ResourceStatus* other);
  friend void swap(ResourceStatus& a, ResourceStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResourceStatus* New() const final {
    return CreateMaybeMessage<ResourceStatus>(nullptr);
  }

  ResourceStatus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResourceStatus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResourceStatus& from);
  void MergeFrom(const ResourceStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .commonmodule.AnalogStatusGGIO analogStatusGGIO = 2 [(.uml.option_multiplicity_min) = 0];
  int analogstatusggio_size() const;
  void clear_analogstatusggio();
  static const int kAnalogStatusGGIOFieldNumber = 2;
  ::commonmodule::AnalogStatusGGIO* mutable_analogstatusggio(int index);
  ::google::protobuf::RepeatedPtrField< ::commonmodule::AnalogStatusGGIO >*
      mutable_analogstatusggio();
  const ::commonmodule::AnalogStatusGGIO& analogstatusggio(int index) const;
  ::commonmodule::AnalogStatusGGIO* add_analogstatusggio();
  const ::google::protobuf::RepeatedPtrField< ::commonmodule::AnalogStatusGGIO >&
      analogstatusggio() const;

  // repeated .commonmodule.BooleanStatusGGIO booleanStatusGGIO = 3 [(.uml.option_multiplicity_min) = 0];
  int booleanstatusggio_size() const;
  void clear_booleanstatusggio();
  static const int kBooleanStatusGGIOFieldNumber = 3;
  ::commonmodule::BooleanStatusGGIO* mutable_booleanstatusggio(int index);
  ::google::protobuf::RepeatedPtrField< ::commonmodule::BooleanStatusGGIO >*
      mutable_booleanstatusggio();
  const ::commonmodule::BooleanStatusGGIO& booleanstatusggio(int index) const;
  ::commonmodule::BooleanStatusGGIO* add_booleanstatusggio();
  const ::google::protobuf::RepeatedPtrField< ::commonmodule::BooleanStatusGGIO >&
      booleanstatusggio() const;

  // repeated .commonmodule.IntegerStatusGGIO integerStatusGGIO = 4 [(.uml.option_multiplicity_min) = 0];
  int integerstatusggio_size() const;
  void clear_integerstatusggio();
  static const int kIntegerStatusGGIOFieldNumber = 4;
  ::commonmodule::IntegerStatusGGIO* mutable_integerstatusggio(int index);
  ::google::protobuf::RepeatedPtrField< ::commonmodule::IntegerStatusGGIO >*
      mutable_integerstatusggio();
  const ::commonmodule::IntegerStatusGGIO& integerstatusggio(int index) const;
  ::commonmodule::IntegerStatusGGIO* add_integerstatusggio();
  const ::google::protobuf::RepeatedPtrField< ::commonmodule::IntegerStatusGGIO >&
      integerstatusggio() const;

  // repeated .commonmodule.StringStatusGGIO stringStatusGGIO = 5 [(.uml.option_multiplicity_min) = 0];
  int stringstatusggio_size() const;
  void clear_stringstatusggio();
  static const int kStringStatusGGIOFieldNumber = 5;
  ::commonmodule::StringStatusGGIO* mutable_stringstatusggio(int index);
  ::google::protobuf::RepeatedPtrField< ::commonmodule::StringStatusGGIO >*
      mutable_stringstatusggio();
  const ::commonmodule::StringStatusGGIO& stringstatusggio(int index) const;
  ::commonmodule::StringStatusGGIO* add_stringstatusggio();
  const ::google::protobuf::RepeatedPtrField< ::commonmodule::StringStatusGGIO >&
      stringstatusggio() const;

  // .commonmodule.StatusValue statusValue = 1 [(.uml.option_parent_message) = true];
  bool has_statusvalue() const;
  void clear_statusvalue();
  static const int kStatusValueFieldNumber = 1;
  const ::commonmodule::StatusValue& statusvalue() const;
  ::commonmodule::StatusValue* release_statusvalue();
  ::commonmodule::StatusValue* mutable_statusvalue();
  void set_allocated_statusvalue(::commonmodule::StatusValue* statusvalue);

  // @@protoc_insertion_point(class_scope:resourcemodule.ResourceStatus)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::commonmodule::AnalogStatusGGIO > analogstatusggio_;
  ::google::protobuf::RepeatedPtrField< ::commonmodule::BooleanStatusGGIO > booleanstatusggio_;
  ::google::protobuf::RepeatedPtrField< ::commonmodule::IntegerStatusGGIO > integerstatusggio_;
  ::google::protobuf::RepeatedPtrField< ::commonmodule::StringStatusGGIO > stringstatusggio_;
  ::commonmodule::StatusValue* statusvalue_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_resourcemodule_2fresourcemodule_2eproto;
};
// -------------------------------------------------------------------

class ResourceStatusProfile :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:resourcemodule.ResourceStatusProfile) */ {
 public:
  ResourceStatusProfile();
  virtual ~ResourceStatusProfile();

  ResourceStatusProfile(const ResourceStatusProfile& from);

  inline ResourceStatusProfile& operator=(const ResourceStatusProfile& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResourceStatusProfile(ResourceStatusProfile&& from) noexcept
    : ResourceStatusProfile() {
    *this = ::std::move(from);
  }

  inline ResourceStatusProfile& operator=(ResourceStatusProfile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ResourceStatusProfile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResourceStatusProfile* internal_default_instance() {
    return reinterpret_cast<const ResourceStatusProfile*>(
               &_ResourceStatusProfile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ResourceStatusProfile* other);
  friend void swap(ResourceStatusProfile& a, ResourceStatusProfile& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResourceStatusProfile* New() const final {
    return CreateMaybeMessage<ResourceStatusProfile>(nullptr);
  }

  ResourceStatusProfile* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResourceStatusProfile>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResourceStatusProfile& from);
  void MergeFrom(const ResourceStatusProfile& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceStatusProfile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .commonmodule.StatusMessageInfo statusMessageInfo = 1 [(.uml.option_parent_message) = true];
  bool has_statusmessageinfo() const;
  void clear_statusmessageinfo();
  static const int kStatusMessageInfoFieldNumber = 1;
  const ::commonmodule::StatusMessageInfo& statusmessageinfo() const;
  ::commonmodule::StatusMessageInfo* release_statusmessageinfo();
  ::commonmodule::StatusMessageInfo* mutable_statusmessageinfo();
  void set_allocated_statusmessageinfo(::commonmodule::StatusMessageInfo* statusmessageinfo);

  // .commonmodule.ConductingEquipment conductingEquipment = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  bool has_conductingequipment() const;
  void clear_conductingequipment();
  static const int kConductingEquipmentFieldNumber = 2;
  const ::commonmodule::ConductingEquipment& conductingequipment() const;
  ::commonmodule::ConductingEquipment* release_conductingequipment();
  ::commonmodule::ConductingEquipment* mutable_conductingequipment();
  void set_allocated_conductingequipment(::commonmodule::ConductingEquipment* conductingequipment);

  // .commonmodule.IED ied = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  bool has_ied() const;
  void clear_ied();
  static const int kIedFieldNumber = 3;
  const ::commonmodule::IED& ied() const;
  ::commonmodule::IED* release_ied();
  ::commonmodule::IED* mutable_ied();
  void set_allocated_ied(::commonmodule::IED* ied);

  // .resourcemodule.ResourceStatus resourceStatus = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
  bool has_resourcestatus() const;
  void clear_resourcestatus();
  static const int kResourceStatusFieldNumber = 4;
  const ::resourcemodule::ResourceStatus& resourcestatus() const;
  ::resourcemodule::ResourceStatus* release_resourcestatus();
  ::resourcemodule::ResourceStatus* mutable_resourcestatus();
  void set_allocated_resourcestatus(::resourcemodule::ResourceStatus* resourcestatus);

  // @@protoc_insertion_point(class_scope:resourcemodule.ResourceStatusProfile)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::commonmodule::StatusMessageInfo* statusmessageinfo_;
  ::commonmodule::ConductingEquipment* conductingequipment_;
  ::commonmodule::IED* ied_;
  ::resourcemodule::ResourceStatus* resourcestatus_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_resourcemodule_2fresourcemodule_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResourceReading

// .commonmodule.ConductingEquipmentTerminalReading conductingEquipmentTerminalReading = 1 [(.uml.option_parent_message) = true];
inline bool ResourceReading::has_conductingequipmentterminalreading() const {
  return this != internal_default_instance() && conductingequipmentterminalreading_ != nullptr;
}
inline const ::commonmodule::ConductingEquipmentTerminalReading& ResourceReading::conductingequipmentterminalreading() const {
  const ::commonmodule::ConductingEquipmentTerminalReading* p = conductingequipmentterminalreading_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReading.conductingEquipmentTerminalReading)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::ConductingEquipmentTerminalReading*>(
      &::commonmodule::_ConductingEquipmentTerminalReading_default_instance_);
}
inline ::commonmodule::ConductingEquipmentTerminalReading* ResourceReading::release_conductingequipmentterminalreading() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReading.conductingEquipmentTerminalReading)
  
  ::commonmodule::ConductingEquipmentTerminalReading* temp = conductingequipmentterminalreading_;
  conductingequipmentterminalreading_ = nullptr;
  return temp;
}
inline ::commonmodule::ConductingEquipmentTerminalReading* ResourceReading::mutable_conductingequipmentterminalreading() {
  
  if (conductingequipmentterminalreading_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::ConductingEquipmentTerminalReading>(GetArenaNoVirtual());
    conductingequipmentterminalreading_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReading.conductingEquipmentTerminalReading)
  return conductingequipmentterminalreading_;
}
inline void ResourceReading::set_allocated_conductingequipmentterminalreading(::commonmodule::ConductingEquipmentTerminalReading* conductingequipmentterminalreading) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(conductingequipmentterminalreading_);
  }
  if (conductingequipmentterminalreading) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      conductingequipmentterminalreading = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, conductingequipmentterminalreading, submessage_arena);
    }
    
  } else {
    
  }
  conductingequipmentterminalreading_ = conductingequipmentterminalreading;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReading.conductingEquipmentTerminalReading)
}

// .commonmodule.PhaseMMTN phaseMMTN = 2;
inline bool ResourceReading::has_phasemmtn() const {
  return this != internal_default_instance() && phasemmtn_ != nullptr;
}
inline const ::commonmodule::PhaseMMTN& ResourceReading::phasemmtn() const {
  const ::commonmodule::PhaseMMTN* p = phasemmtn_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReading.phaseMMTN)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::PhaseMMTN*>(
      &::commonmodule::_PhaseMMTN_default_instance_);
}
inline ::commonmodule::PhaseMMTN* ResourceReading::release_phasemmtn() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReading.phaseMMTN)
  
  ::commonmodule::PhaseMMTN* temp = phasemmtn_;
  phasemmtn_ = nullptr;
  return temp;
}
inline ::commonmodule::PhaseMMTN* ResourceReading::mutable_phasemmtn() {
  
  if (phasemmtn_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::PhaseMMTN>(GetArenaNoVirtual());
    phasemmtn_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReading.phaseMMTN)
  return phasemmtn_;
}
inline void ResourceReading::set_allocated_phasemmtn(::commonmodule::PhaseMMTN* phasemmtn) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(phasemmtn_);
  }
  if (phasemmtn) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      phasemmtn = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, phasemmtn, submessage_arena);
    }
    
  } else {
    
  }
  phasemmtn_ = phasemmtn;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReading.phaseMMTN)
}

// .commonmodule.ReadingMMTR readingMMTR = 3;
inline bool ResourceReading::has_readingmmtr() const {
  return this != internal_default_instance() && readingmmtr_ != nullptr;
}
inline const ::commonmodule::ReadingMMTR& ResourceReading::readingmmtr() const {
  const ::commonmodule::ReadingMMTR* p = readingmmtr_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReading.readingMMTR)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::ReadingMMTR*>(
      &::commonmodule::_ReadingMMTR_default_instance_);
}
inline ::commonmodule::ReadingMMTR* ResourceReading::release_readingmmtr() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReading.readingMMTR)
  
  ::commonmodule::ReadingMMTR* temp = readingmmtr_;
  readingmmtr_ = nullptr;
  return temp;
}
inline ::commonmodule::ReadingMMTR* ResourceReading::mutable_readingmmtr() {
  
  if (readingmmtr_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::ReadingMMTR>(GetArenaNoVirtual());
    readingmmtr_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReading.readingMMTR)
  return readingmmtr_;
}
inline void ResourceReading::set_allocated_readingmmtr(::commonmodule::ReadingMMTR* readingmmtr) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(readingmmtr_);
  }
  if (readingmmtr) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      readingmmtr = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, readingmmtr, submessage_arena);
    }
    
  } else {
    
  }
  readingmmtr_ = readingmmtr;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReading.readingMMTR)
}

// .commonmodule.ReadingMMXU readingMMXU = 4;
inline bool ResourceReading::has_readingmmxu() const {
  return this != internal_default_instance() && readingmmxu_ != nullptr;
}
inline const ::commonmodule::ReadingMMXU& ResourceReading::readingmmxu() const {
  const ::commonmodule::ReadingMMXU* p = readingmmxu_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReading.readingMMXU)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::ReadingMMXU*>(
      &::commonmodule::_ReadingMMXU_default_instance_);
}
inline ::commonmodule::ReadingMMXU* ResourceReading::release_readingmmxu() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReading.readingMMXU)
  
  ::commonmodule::ReadingMMXU* temp = readingmmxu_;
  readingmmxu_ = nullptr;
  return temp;
}
inline ::commonmodule::ReadingMMXU* ResourceReading::mutable_readingmmxu() {
  
  if (readingmmxu_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::ReadingMMXU>(GetArenaNoVirtual());
    readingmmxu_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReading.readingMMXU)
  return readingmmxu_;
}
inline void ResourceReading::set_allocated_readingmmxu(::commonmodule::ReadingMMXU* readingmmxu) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(readingmmxu_);
  }
  if (readingmmxu) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      readingmmxu = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, readingmmxu, submessage_arena);
    }
    
  } else {
    
  }
  readingmmxu_ = readingmmxu;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReading.readingMMXU)
}

// -------------------------------------------------------------------

// ResourceReadingProfile

// .commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];
inline bool ResourceReadingProfile::has_readingmessageinfo() const {
  return this != internal_default_instance() && readingmessageinfo_ != nullptr;
}
inline const ::commonmodule::ReadingMessageInfo& ResourceReadingProfile::readingmessageinfo() const {
  const ::commonmodule::ReadingMessageInfo* p = readingmessageinfo_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReadingProfile.readingMessageInfo)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::ReadingMessageInfo*>(
      &::commonmodule::_ReadingMessageInfo_default_instance_);
}
inline ::commonmodule::ReadingMessageInfo* ResourceReadingProfile::release_readingmessageinfo() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReadingProfile.readingMessageInfo)
  
  ::commonmodule::ReadingMessageInfo* temp = readingmessageinfo_;
  readingmessageinfo_ = nullptr;
  return temp;
}
inline ::commonmodule::ReadingMessageInfo* ResourceReadingProfile::mutable_readingmessageinfo() {
  
  if (readingmessageinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::ReadingMessageInfo>(GetArenaNoVirtual());
    readingmessageinfo_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReadingProfile.readingMessageInfo)
  return readingmessageinfo_;
}
inline void ResourceReadingProfile::set_allocated_readingmessageinfo(::commonmodule::ReadingMessageInfo* readingmessageinfo) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(readingmessageinfo_);
  }
  if (readingmessageinfo) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      readingmessageinfo = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, readingmessageinfo, submessage_arena);
    }
    
  } else {
    
  }
  readingmessageinfo_ = readingmessageinfo;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReadingProfile.readingMessageInfo)
}

// .commonmodule.ConductingEquipment conductingEquipment = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
inline bool ResourceReadingProfile::has_conductingequipment() const {
  return this != internal_default_instance() && conductingequipment_ != nullptr;
}
inline const ::commonmodule::ConductingEquipment& ResourceReadingProfile::conductingequipment() const {
  const ::commonmodule::ConductingEquipment* p = conductingequipment_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReadingProfile.conductingEquipment)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::ConductingEquipment*>(
      &::commonmodule::_ConductingEquipment_default_instance_);
}
inline ::commonmodule::ConductingEquipment* ResourceReadingProfile::release_conductingequipment() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReadingProfile.conductingEquipment)
  
  ::commonmodule::ConductingEquipment* temp = conductingequipment_;
  conductingequipment_ = nullptr;
  return temp;
}
inline ::commonmodule::ConductingEquipment* ResourceReadingProfile::mutable_conductingequipment() {
  
  if (conductingequipment_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::ConductingEquipment>(GetArenaNoVirtual());
    conductingequipment_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReadingProfile.conductingEquipment)
  return conductingequipment_;
}
inline void ResourceReadingProfile::set_allocated_conductingequipment(::commonmodule::ConductingEquipment* conductingequipment) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(conductingequipment_);
  }
  if (conductingequipment) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      conductingequipment = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, conductingequipment, submessage_arena);
    }
    
  } else {
    
  }
  conductingequipment_ = conductingequipment;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReadingProfile.conductingEquipment)
}

// .commonmodule.IED ied = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
inline bool ResourceReadingProfile::has_ied() const {
  return this != internal_default_instance() && ied_ != nullptr;
}
inline const ::commonmodule::IED& ResourceReadingProfile::ied() const {
  const ::commonmodule::IED* p = ied_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReadingProfile.ied)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::IED*>(
      &::commonmodule::_IED_default_instance_);
}
inline ::commonmodule::IED* ResourceReadingProfile::release_ied() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReadingProfile.ied)
  
  ::commonmodule::IED* temp = ied_;
  ied_ = nullptr;
  return temp;
}
inline ::commonmodule::IED* ResourceReadingProfile::mutable_ied() {
  
  if (ied_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::IED>(GetArenaNoVirtual());
    ied_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReadingProfile.ied)
  return ied_;
}
inline void ResourceReadingProfile::set_allocated_ied(::commonmodule::IED* ied) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(ied_);
  }
  if (ied) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ied = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ied, submessage_arena);
    }
    
  } else {
    
  }
  ied_ = ied;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReadingProfile.ied)
}

// .resourcemodule.ResourceReading resourceReading = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
inline bool ResourceReadingProfile::has_resourcereading() const {
  return this != internal_default_instance() && resourcereading_ != nullptr;
}
inline void ResourceReadingProfile::clear_resourcereading() {
  if (GetArenaNoVirtual() == nullptr && resourcereading_ != nullptr) {
    delete resourcereading_;
  }
  resourcereading_ = nullptr;
}
inline const ::resourcemodule::ResourceReading& ResourceReadingProfile::resourcereading() const {
  const ::resourcemodule::ResourceReading* p = resourcereading_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceReadingProfile.resourceReading)
  return p != nullptr ? *p : *reinterpret_cast<const ::resourcemodule::ResourceReading*>(
      &::resourcemodule::_ResourceReading_default_instance_);
}
inline ::resourcemodule::ResourceReading* ResourceReadingProfile::release_resourcereading() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceReadingProfile.resourceReading)
  
  ::resourcemodule::ResourceReading* temp = resourcereading_;
  resourcereading_ = nullptr;
  return temp;
}
inline ::resourcemodule::ResourceReading* ResourceReadingProfile::mutable_resourcereading() {
  
  if (resourcereading_ == nullptr) {
    auto* p = CreateMaybeMessage<::resourcemodule::ResourceReading>(GetArenaNoVirtual());
    resourcereading_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceReadingProfile.resourceReading)
  return resourcereading_;
}
inline void ResourceReadingProfile::set_allocated_resourcereading(::resourcemodule::ResourceReading* resourcereading) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete resourcereading_;
  }
  if (resourcereading) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resourcereading = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resourcereading, submessage_arena);
    }
    
  } else {
    
  }
  resourcereading_ = resourcereading;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceReadingProfile.resourceReading)
}

// -------------------------------------------------------------------

// ResourceStatus

// .commonmodule.StatusValue statusValue = 1 [(.uml.option_parent_message) = true];
inline bool ResourceStatus::has_statusvalue() const {
  return this != internal_default_instance() && statusvalue_ != nullptr;
}
inline const ::commonmodule::StatusValue& ResourceStatus::statusvalue() const {
  const ::commonmodule::StatusValue* p = statusvalue_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatus.statusValue)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::StatusValue*>(
      &::commonmodule::_StatusValue_default_instance_);
}
inline ::commonmodule::StatusValue* ResourceStatus::release_statusvalue() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceStatus.statusValue)
  
  ::commonmodule::StatusValue* temp = statusvalue_;
  statusvalue_ = nullptr;
  return temp;
}
inline ::commonmodule::StatusValue* ResourceStatus::mutable_statusvalue() {
  
  if (statusvalue_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::StatusValue>(GetArenaNoVirtual());
    statusvalue_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatus.statusValue)
  return statusvalue_;
}
inline void ResourceStatus::set_allocated_statusvalue(::commonmodule::StatusValue* statusvalue) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(statusvalue_);
  }
  if (statusvalue) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      statusvalue = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, statusvalue, submessage_arena);
    }
    
  } else {
    
  }
  statusvalue_ = statusvalue;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceStatus.statusValue)
}

// repeated .commonmodule.AnalogStatusGGIO analogStatusGGIO = 2 [(.uml.option_multiplicity_min) = 0];
inline int ResourceStatus::analogstatusggio_size() const {
  return analogstatusggio_.size();
}
inline ::commonmodule::AnalogStatusGGIO* ResourceStatus::mutable_analogstatusggio(int index) {
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatus.analogStatusGGIO)
  return analogstatusggio_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::commonmodule::AnalogStatusGGIO >*
ResourceStatus::mutable_analogstatusggio() {
  // @@protoc_insertion_point(field_mutable_list:resourcemodule.ResourceStatus.analogStatusGGIO)
  return &analogstatusggio_;
}
inline const ::commonmodule::AnalogStatusGGIO& ResourceStatus::analogstatusggio(int index) const {
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatus.analogStatusGGIO)
  return analogstatusggio_.Get(index);
}
inline ::commonmodule::AnalogStatusGGIO* ResourceStatus::add_analogstatusggio() {
  // @@protoc_insertion_point(field_add:resourcemodule.ResourceStatus.analogStatusGGIO)
  return analogstatusggio_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::commonmodule::AnalogStatusGGIO >&
ResourceStatus::analogstatusggio() const {
  // @@protoc_insertion_point(field_list:resourcemodule.ResourceStatus.analogStatusGGIO)
  return analogstatusggio_;
}

// repeated .commonmodule.BooleanStatusGGIO booleanStatusGGIO = 3 [(.uml.option_multiplicity_min) = 0];
inline int ResourceStatus::booleanstatusggio_size() const {
  return booleanstatusggio_.size();
}
inline ::commonmodule::BooleanStatusGGIO* ResourceStatus::mutable_booleanstatusggio(int index) {
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatus.booleanStatusGGIO)
  return booleanstatusggio_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::commonmodule::BooleanStatusGGIO >*
ResourceStatus::mutable_booleanstatusggio() {
  // @@protoc_insertion_point(field_mutable_list:resourcemodule.ResourceStatus.booleanStatusGGIO)
  return &booleanstatusggio_;
}
inline const ::commonmodule::BooleanStatusGGIO& ResourceStatus::booleanstatusggio(int index) const {
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatus.booleanStatusGGIO)
  return booleanstatusggio_.Get(index);
}
inline ::commonmodule::BooleanStatusGGIO* ResourceStatus::add_booleanstatusggio() {
  // @@protoc_insertion_point(field_add:resourcemodule.ResourceStatus.booleanStatusGGIO)
  return booleanstatusggio_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::commonmodule::BooleanStatusGGIO >&
ResourceStatus::booleanstatusggio() const {
  // @@protoc_insertion_point(field_list:resourcemodule.ResourceStatus.booleanStatusGGIO)
  return booleanstatusggio_;
}

// repeated .commonmodule.IntegerStatusGGIO integerStatusGGIO = 4 [(.uml.option_multiplicity_min) = 0];
inline int ResourceStatus::integerstatusggio_size() const {
  return integerstatusggio_.size();
}
inline ::commonmodule::IntegerStatusGGIO* ResourceStatus::mutable_integerstatusggio(int index) {
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatus.integerStatusGGIO)
  return integerstatusggio_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::commonmodule::IntegerStatusGGIO >*
ResourceStatus::mutable_integerstatusggio() {
  // @@protoc_insertion_point(field_mutable_list:resourcemodule.ResourceStatus.integerStatusGGIO)
  return &integerstatusggio_;
}
inline const ::commonmodule::IntegerStatusGGIO& ResourceStatus::integerstatusggio(int index) const {
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatus.integerStatusGGIO)
  return integerstatusggio_.Get(index);
}
inline ::commonmodule::IntegerStatusGGIO* ResourceStatus::add_integerstatusggio() {
  // @@protoc_insertion_point(field_add:resourcemodule.ResourceStatus.integerStatusGGIO)
  return integerstatusggio_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::commonmodule::IntegerStatusGGIO >&
ResourceStatus::integerstatusggio() const {
  // @@protoc_insertion_point(field_list:resourcemodule.ResourceStatus.integerStatusGGIO)
  return integerstatusggio_;
}

// repeated .commonmodule.StringStatusGGIO stringStatusGGIO = 5 [(.uml.option_multiplicity_min) = 0];
inline int ResourceStatus::stringstatusggio_size() const {
  return stringstatusggio_.size();
}
inline ::commonmodule::StringStatusGGIO* ResourceStatus::mutable_stringstatusggio(int index) {
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatus.stringStatusGGIO)
  return stringstatusggio_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::commonmodule::StringStatusGGIO >*
ResourceStatus::mutable_stringstatusggio() {
  // @@protoc_insertion_point(field_mutable_list:resourcemodule.ResourceStatus.stringStatusGGIO)
  return &stringstatusggio_;
}
inline const ::commonmodule::StringStatusGGIO& ResourceStatus::stringstatusggio(int index) const {
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatus.stringStatusGGIO)
  return stringstatusggio_.Get(index);
}
inline ::commonmodule::StringStatusGGIO* ResourceStatus::add_stringstatusggio() {
  // @@protoc_insertion_point(field_add:resourcemodule.ResourceStatus.stringStatusGGIO)
  return stringstatusggio_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::commonmodule::StringStatusGGIO >&
ResourceStatus::stringstatusggio() const {
  // @@protoc_insertion_point(field_list:resourcemodule.ResourceStatus.stringStatusGGIO)
  return stringstatusggio_;
}

// -------------------------------------------------------------------

// ResourceStatusProfile

// .commonmodule.StatusMessageInfo statusMessageInfo = 1 [(.uml.option_parent_message) = true];
inline bool ResourceStatusProfile::has_statusmessageinfo() const {
  return this != internal_default_instance() && statusmessageinfo_ != nullptr;
}
inline const ::commonmodule::StatusMessageInfo& ResourceStatusProfile::statusmessageinfo() const {
  const ::commonmodule::StatusMessageInfo* p = statusmessageinfo_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatusProfile.statusMessageInfo)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::StatusMessageInfo*>(
      &::commonmodule::_StatusMessageInfo_default_instance_);
}
inline ::commonmodule::StatusMessageInfo* ResourceStatusProfile::release_statusmessageinfo() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceStatusProfile.statusMessageInfo)
  
  ::commonmodule::StatusMessageInfo* temp = statusmessageinfo_;
  statusmessageinfo_ = nullptr;
  return temp;
}
inline ::commonmodule::StatusMessageInfo* ResourceStatusProfile::mutable_statusmessageinfo() {
  
  if (statusmessageinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::StatusMessageInfo>(GetArenaNoVirtual());
    statusmessageinfo_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatusProfile.statusMessageInfo)
  return statusmessageinfo_;
}
inline void ResourceStatusProfile::set_allocated_statusmessageinfo(::commonmodule::StatusMessageInfo* statusmessageinfo) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(statusmessageinfo_);
  }
  if (statusmessageinfo) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      statusmessageinfo = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, statusmessageinfo, submessage_arena);
    }
    
  } else {
    
  }
  statusmessageinfo_ = statusmessageinfo;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceStatusProfile.statusMessageInfo)
}

// .commonmodule.ConductingEquipment conductingEquipment = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
inline bool ResourceStatusProfile::has_conductingequipment() const {
  return this != internal_default_instance() && conductingequipment_ != nullptr;
}
inline const ::commonmodule::ConductingEquipment& ResourceStatusProfile::conductingequipment() const {
  const ::commonmodule::ConductingEquipment* p = conductingequipment_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatusProfile.conductingEquipment)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::ConductingEquipment*>(
      &::commonmodule::_ConductingEquipment_default_instance_);
}
inline ::commonmodule::ConductingEquipment* ResourceStatusProfile::release_conductingequipment() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceStatusProfile.conductingEquipment)
  
  ::commonmodule::ConductingEquipment* temp = conductingequipment_;
  conductingequipment_ = nullptr;
  return temp;
}
inline ::commonmodule::ConductingEquipment* ResourceStatusProfile::mutable_conductingequipment() {
  
  if (conductingequipment_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::ConductingEquipment>(GetArenaNoVirtual());
    conductingequipment_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatusProfile.conductingEquipment)
  return conductingequipment_;
}
inline void ResourceStatusProfile::set_allocated_conductingequipment(::commonmodule::ConductingEquipment* conductingequipment) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(conductingequipment_);
  }
  if (conductingequipment) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      conductingequipment = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, conductingequipment, submessage_arena);
    }
    
  } else {
    
  }
  conductingequipment_ = conductingequipment;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceStatusProfile.conductingEquipment)
}

// .commonmodule.IED ied = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
inline bool ResourceStatusProfile::has_ied() const {
  return this != internal_default_instance() && ied_ != nullptr;
}
inline const ::commonmodule::IED& ResourceStatusProfile::ied() const {
  const ::commonmodule::IED* p = ied_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatusProfile.ied)
  return p != nullptr ? *p : *reinterpret_cast<const ::commonmodule::IED*>(
      &::commonmodule::_IED_default_instance_);
}
inline ::commonmodule::IED* ResourceStatusProfile::release_ied() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceStatusProfile.ied)
  
  ::commonmodule::IED* temp = ied_;
  ied_ = nullptr;
  return temp;
}
inline ::commonmodule::IED* ResourceStatusProfile::mutable_ied() {
  
  if (ied_ == nullptr) {
    auto* p = CreateMaybeMessage<::commonmodule::IED>(GetArenaNoVirtual());
    ied_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatusProfile.ied)
  return ied_;
}
inline void ResourceStatusProfile::set_allocated_ied(::commonmodule::IED* ied) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(ied_);
  }
  if (ied) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ied = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ied, submessage_arena);
    }
    
  } else {
    
  }
  ied_ = ied;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceStatusProfile.ied)
}

// .resourcemodule.ResourceStatus resourceStatus = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];
inline bool ResourceStatusProfile::has_resourcestatus() const {
  return this != internal_default_instance() && resourcestatus_ != nullptr;
}
inline void ResourceStatusProfile::clear_resourcestatus() {
  if (GetArenaNoVirtual() == nullptr && resourcestatus_ != nullptr) {
    delete resourcestatus_;
  }
  resourcestatus_ = nullptr;
}
inline const ::resourcemodule::ResourceStatus& ResourceStatusProfile::resourcestatus() const {
  const ::resourcemodule::ResourceStatus* p = resourcestatus_;
  // @@protoc_insertion_point(field_get:resourcemodule.ResourceStatusProfile.resourceStatus)
  return p != nullptr ? *p : *reinterpret_cast<const ::resourcemodule::ResourceStatus*>(
      &::resourcemodule::_ResourceStatus_default_instance_);
}
inline ::resourcemodule::ResourceStatus* ResourceStatusProfile::release_resourcestatus() {
  // @@protoc_insertion_point(field_release:resourcemodule.ResourceStatusProfile.resourceStatus)
  
  ::resourcemodule::ResourceStatus* temp = resourcestatus_;
  resourcestatus_ = nullptr;
  return temp;
}
inline ::resourcemodule::ResourceStatus* ResourceStatusProfile::mutable_resourcestatus() {
  
  if (resourcestatus_ == nullptr) {
    auto* p = CreateMaybeMessage<::resourcemodule::ResourceStatus>(GetArenaNoVirtual());
    resourcestatus_ = p;
  }
  // @@protoc_insertion_point(field_mutable:resourcemodule.ResourceStatusProfile.resourceStatus)
  return resourcestatus_;
}
inline void ResourceStatusProfile::set_allocated_resourcestatus(::resourcemodule::ResourceStatus* resourcestatus) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete resourcestatus_;
  }
  if (resourcestatus) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      resourcestatus = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resourcestatus, submessage_arena);
    }
    
  } else {
    
  }
  resourcestatus_ = resourcestatus;
  // @@protoc_insertion_point(field_set_allocated:resourcemodule.ResourceStatusProfile.resourceStatus)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace resourcemodule

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_resourcemodule_2fresourcemodule_2eproto
